// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWuxXDPstp7WWse1sMZX6IQBjmPE3bLpg',
    appId: '1:910952229548:web:51b0c3fb34bc2d119b4d09',
    messagingSenderId: '910952229548',
    projectId: 'flutter-fitness-232cc',
    authDomain: 'flutter-fitness-232cc.firebaseapp.com',
    storageBucket: 'flutter-fitness-232cc.appspot.com',
    measurementId: 'G-VHJREXLZ4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA57Rxp6j7QCFrzfNmRa85BvwnZyW9HwWs',
    appId: '1:910952229548:android:318ed4b62d8ac9849b4d09',
    messagingSenderId: '910952229548',
    projectId: 'flutter-fitness-232cc',
    storageBucket: 'flutter-fitness-232cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKupu_Svg6LnjazVAEV6NEZDPgM4JNyBk',
    appId: '1:910952229548:ios:fd7238c56d17728c9b4d09',
    messagingSenderId: '910952229548',
    projectId: 'flutter-fitness-232cc',
    storageBucket: 'flutter-fitness-232cc.appspot.com',
    iosClientId: '910952229548-mopg7gltc6pu7u13ephdg9l8ih68efbg.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKupu_Svg6LnjazVAEV6NEZDPgM4JNyBk',
    appId: '1:910952229548:ios:fd7238c56d17728c9b4d09',
    messagingSenderId: '910952229548',
    projectId: 'flutter-fitness-232cc',
    storageBucket: 'flutter-fitness-232cc.appspot.com',
    iosClientId: '910952229548-mopg7gltc6pu7u13ephdg9l8ih68efbg.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessApp',
  );
}
